# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75f0b5d5de595e3e747a31c3c5555c57d378f81eb10471bf6c40d8b6d451b8e5060ace446ade99d189a566898f5d5b76e5424d81e89ee89b7db7b7b2ed20c202

test:
  secret_key_base: 217553472bb0390432d8bae215cdabd951a56d47f091feb23cd4ce93288490247fba350d4d25ea5a2136cc079001d00afce61b73636295816a1de908d76d6cb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
